[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "scenographer"
version = "0.1.1"
description = "The cool dude who sets up the stage. Word."
authors = ["Xavier Francisco <xavier@zyper.com>"]
readme = 'README.md'
keywords = ["postgres", "subset", "sample"]
homepage = "https://zyperco.github.io/scenographer/"
documentation = "https://zyperco.github.io/scenographer/"
repository = "https://github.com/zyperco/scenographer/"

[tool.poetry.dependencies]
python = "^3.8"
sqlalchemy_utils = "^0.36.8"
sqlalchemy-postgres-copy = "^0.5.0"
sqlalchemy = "^1.3.19"
psycopg2-binary = "^2.8.5"
networkx = "^2.5"
docopt = "^0.6.2"
loguru = "^0.5.1"
pyrsistent = "^0.16.0"
matplotlib = "^3.1.2"
commentjson = "^0.8.3"
dict-digger = "^0.2.1"

[tool.poetry.dev-dependencies]
ipython = "^7.18.1"
pdoc3 = "^0.9.1"
pylint = "^2.6.0"
pytest = "^6.2.1"
isort = "^5.4.2"
black = "^20.8b1"
flake8 = "^3.8.3"

[tool.poetry.scripts]
scenographer = "scenographer.cli:cli"
